accounts/urls.py
from django.conf.urls import url 
from . import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.urls import reverse
urlpatterns = [
	url(r'^$', views.home),
	url(r'^login/$', login, {'template_name':'accounts/login.html'}, name = 'login'),
	url(r'^logout/$', logout, {'template_name':"accounts/logout.html"}, name = 'logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^profile/$', views.view_profile, name='view_profile'),
	url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
	url(r'^change-password/$', views.change_password, name='change_password'),
	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html',
	'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name':'accounts/reset_password_email.html'},
	name='reset_password'),
	url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
	password_reset_confirm, name='password_reset_confirm'),
	url(r'^reset-password/complete/$', password_reset_complete, name='password_reset_complete'),
	url(r'^client/$', views.client, name='client'),
	url(r'^testemail/$', views.testEmail, name='testemail'),
	url(r'^tickets/$', views.tickets, name='tickets'),
	url(r'^tickets/details/$', views.ticket_detail, name='ticket_detail'),
	url(r'^tickets/new/$', views.create_ticket, name='create_ticket'),
	url(r'^tickets/new-entry/$', views.new_entry, name='new_entry'),
	url(r'^tickets/test/$', views.test, name='test'),
	url(r'^tickets/edit/$', views.edit_ticket, name="edit_ticket"),
	url(r'tickets/(?P<cid>[\w\s]+/$)', views.ticket_detail, name='ticket_detail'),
	url(r'tickets/(?P<tech>[\w\s]+/$)', views.ticket_detail, name='ticket_detail'),
	url(r'ajax_req/$', views.ajax_req, name='ajax_req'),

	


]

accounts/forms.py
from django import forms
from django.forms import ModelForm, modelform_factory, ModelChoiceField
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from accounts.models import *
from datetime import *
import time
from bootstrap3_datetime.widgets import DateTimePicker
from django_unixdatetimefield import UnixDateTimeField
from django.utils.dateformat import format



class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email', 
			'password1',
			'password2',
		)

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user 




class EditProfileForm(UserChangeForm):

	class Meta:
		model = User
		fields = (
			'email',
			'first_name',
			'last_name',
			'password'
		)

##Do I need this?
class MyModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj 
##working function
## ticks = serviceticket.timestamp
## datetime(1,1,1) + timedelta(microseconds = ticks/10)
## output should be datetime.datetime(year, month, day, hour, minute, second ...etc)
def testtime(*args, **kwargs):
	dotnet = datetime(1,1,1)
	times = datetime.now()
	unix = times - dotnet
	dotnettimestamp = (((unix.days*60*60*24 + unix.seconds)*1000 + unix.microseconds)*100)*100
	return dotnettimestamp

class NewTicketForm(forms.ModelForm):
	class Meta:
		model = Servicetickets
		fields = ("__all__")
		widgets = {
			#'ticketstartdate':DateTimePicker(options={"format": "YYYY/MM/DD HH:mm:ss"}, attrs={'onchange':'this.form.submit()'}),
			'technician': forms.Select(choices=Technicians.objects.values_list('nickname','nickname')),
			'ticket_title':forms.TextInput(attrs={'placeholder':'title', 'style':'font-size:48px;'}),
			'contact_name':forms.Select(attrs={'placeholder':'contact'}),

			
		}
	
	clientid = forms.IntegerField(widget=forms.Select(choices=Clientlist.objects.values_list('oid','clientname')
		))
	
	#technician = forms.CharField(widget=forms.Select(choices=Technicians.objects.values_list('nickname','nickname')))
	worktype = forms.CharField(widget=forms.Select(choices=Worktypes.objects.values_list('worktype', 'worktype')))
	ticketstartdate = forms.DateTimeField(widget=forms.HiddenInput())
	timestamp = forms.CharField(widget=forms.DateInput(attrs={
		"placeholder":'timestamp', "value":testtime}))
	ticket_status = forms.CharField(widget=forms.Select(choices=Ticketstatuses.objects.values_list('oid','status')))


class NewTicketTimeEntries(forms.ModelForm):
	class Meta:
		model = Timeentries
		fields = ("__all__")
		widgets = {

			'notes':forms.TextInput(attrs={'placeholder':'Entry Notes'}),
			'technician': forms.Select(choices=Technicians.objects.values_list('nickname','nickname')),

		}

	timestamp = forms.CharField(widget=forms.DateInput(attrs={
		"placeholder":"timestamp", "value":testtime})) 
	worktype = forms.CharField(widget=forms.Select(choices=Worktypes.objects.values_list('worktype', 'worktype'))) 
	startdate = forms.DateTimeField(widget=forms.HiddenInput())
	enddate = forms.DateTimeField(widget=forms.HiddenInput())
	
		
		

###works when testtime funtion in here and timestamp value is set to time. Need to figure out how to get time to update when a new instance is called and not
###when code is saved and server restarted. 
class testticket(forms.ModelForm):

	class Meta:
		model = Servicetickets
		fields = ("__all__")
		widgets = {
			#'ticketstartdate':DateTimePicker(options={"format": "YYYY/MM/DD HH:mm:ss"}, attrs={'onchange':'this.form.submit()'}),
			'technician': forms.Select(choices=Technicians.objects.values_list('nickname','nickname')),
			'ticket_title':forms.TextInput(attrs={'placeholder':'title'}),
			'contact_name':forms.TextInput(attrs={'placeholder':'contact'}),
			
		}
	
	clientid = forms.IntegerField(widget=forms.Select(choices=Clientlist.objects.values_list('oid','clientname')
		))
	#technician = forms.CharField(widget=forms.Select(choices=Technicians.objects.values_list('nickname','nickname')))
	worktype = forms.CharField(widget=forms.Select(choices=Worktypes.objects.values_list('worktype', 'worktype')))
	ticketstartdate = forms.DateTimeField(widget=forms.HiddenInput())
	timestamp = forms.CharField(widget=forms.DateInput(attrs={
		"placeholder":'timestamp', "value":testtime}))
	ticket_status = forms.CharField(widget=forms.Select(choices=Ticketstatuses.objects.values_list('oid','status')))


class emailTest(forms.Form):
		subject = forms.CharField(required = True)	
		from_email = forms.EmailField(required=True)		
		message = forms.CharField()
		



	



		
		 
    
		

accounts/templates/accounts/client_profile.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
	<div class="container">
		<div class="row" id="title_row">
			<h1>{{ clientinfo.clientname }}</h1>
			<form method="GET" action="{% url 'accounts:tickets' %}">
				
				<button class="btn btn-default" type='submit' name="cid" value="{{ clientinfo.oid }}">View Service Tickets</button>
			</form>
		</div>
		<div class="row" id="adress_row">
			<h3>Address</h3>
				<h4>
				{{ clientinfo.address1 }} <br/>
				{{ clientinfo.address2 }}
				{{ clientinfo.address3 }}
				{{ clientinfo.city }},{{ clientinfo.state }} {{ clientinfo.zipcode }}
				</h4>
		</div>
		<div class="row" id="contactinfo_row">
			<h3>Contact Information</h3>
				<h4>
				{{ clientinfo.phonenumber }}, ext{{ clientinfo.extension }}<br/>			
				Primary Contact: {{ clientinfo.primarycontact }}<br/>
				Email: {{ clientinfo.email }}<br/>
				Fax Number: {{ clientinfo.fax_number }}<br/>
				{% for contact in contact %}
				{{ contact.contactname }}
				{% endfor %}

		</div>
		<div class="row" id="clientinfo">
			<div class="row">
				<h3>Notes</h3>
			</div>				
				<h4>{{ clientinfo.notes }}<br/>
			<div class="row">
				<h3>Client Type</h3>
			</div>
				{{ type.type }}<br/>
			<div class="row">
				<h3>Do not Assist?</h3>
			</div>
			{{ clientinfo.donotassist|yesno:"Do not assist,Assist" }}<br/>
			</h4>			
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/edit-ticket.html
{% extends 'base.html' %}

{% block body %}


<form method="POST" action="{%  url 'accounts:edit_ticket' %}">
 {{ ticket.ticket_title }}

 {% for timeentries in timeentries %}
 {{ timeentries.notes }}
 {% endfor %}

</form>
{% endblock %}

accounts/templates/accounts/email.html
<form method ="POST">
	{% csrf_token %}
	{{ form }}
	<div class="form-actions">
		<button type="submit">Send</button>
	</div>
</form>

accounts/templates/accounts/error.html
{% block body %}
<form method=POST action="{% url 'accounts:test' %}">
	{% csrf_token %}
 {{ ticket }}
  </ul>

  <button type="submit">SUBMIT THIS THIS</button>
</div>

</form>
   {% if ticket.errors %}
    {% for field in ticket %}
        {% for error in field.errors %}
            <p> {{ errors }} </p>
        {% endfor %}
    {% endfor %}

{% endif %}
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% block head %}
<title>Home</title>
{% endblock %}
{% block body %}
<h1>home page coming through</h1>
<button class="btn btn-default" type="button">Login</button>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block head %}
<title>Logout</title>
{% endblock %}
{% block body %}
<h1>Logged Out</h1>
<h2>You have been logged out</h2>

{% endblock %}

accounts/templates/accounts/multi-page-new-ticket.html
{% block multi-page-new-ticket %}
<form method=POST action="{% url 'accounts:create_ticket' %}">
    {% csrf_token %}
   

    <fieldset id="first">
        <h2>Enter new ticket title</h2>
        {{ ticket.ticket_title }}
        
        <div class="container" style="padding:30px";>
        {% include 'accounts/form_templates/datepicker_modal.html' with a=ticket.ticketstartdate %}
        </div>
        
        <h2>Tecnhician</h2> 
        {{ ticket.technician }}
        
        <h2>Client name</h2>
        {{ ticket.clientid }}

        <h2>Send Complete Email To:</h2>
        <div id="hotness">
        </div>

        <h2>Contact name</h2>
        {{ ticket.contact_name }}
        
        
        <h2>Work type</h2>
        {{ ticket.worktype }}
        
        <h2>Ticket status</h2>
        {{ ticket.ticket_status }}
        (timestamp **needs to be hidden)
        {{ ticket.timestamp }}
        <input class="next_btn" type="button" value="Next">
    </fieldset>
   
    
    <fieldset>
        <h4>for debugging</h4>
        {{ tid.ticketid }}
        {{ entries.timestamp }}
        <h2>Entry details</h2>
        <h3>Technician</h3>
        {{ entries.technician }}        
        <h3>Work Type</h3>
        {{ entries.worktype }}
        <h3>Notes</h3>
        {{ entries.notes }}
        <h3>Total Time Spent On Ticket</h3>    
        {{ ticket.time_spent_minutes_field }}
        <div class='container'>
        {% include 'accounts/form_templates/datepicker_modal.html' with a=entries.startdate %}
   
        {% include 'accounts/form_templates/datepicker_modal.html' with a=entries.enddate %}
        </div>

        <button style="background-color:green; margin:5em;" class="btn btn-lg" type='submit'>Submit</button>

        <button type='submit'>Submit</button>
    </fieldset>
       
</form>
{% endblock %}

 

accounts/templates/accounts/new-ticketmain.html
{% extends "base.html" %} 


{% block title %}
    <h3>New Ticket</h3>
{% endblock %}

{% block body %}

{% block multi-page-new-ticket %}
{% include "accounts/multi-page-new-ticket.html" %}
{% endblock %}

{% endblock %}


{% block script %}


<script>
  
    $('#id_clientid').change(function(event){
      
        var urls = $('#ajax_url').attr('href');
        var  clientid = $('#id_clientid');
        $.ajax({
            type: "POST",
            dataType: "json",
            url: urls,
            data: {
                'clientid' : $('#id_clientid').val(), csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(result) {
                $.each(result, function(index, value) {
                    $('#id_contact_name')
                        .append($("<option></option>")
                                .attr("value",value.fields.contactname)
                                .text(value.fields.contactname));
                });

            },
            error: function (error) {
                alert("Error with Ajax, You SUCK");
            }
        });
    });


</script>
{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class='container'>
<h1>Register</h1>
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<button class='btn btn-default' type='submit'>Create</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
	{% load i18n %}{% autoescape off %}
	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
	
	{% trans "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

	{% trans "Thanks for using our site!" %}
	
	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
	
	{% endautoescape %}
	

accounts/templates/accounts/ticket-details.html
{% extends 'base.html' %}

{% block body %}
<div class="row" id="status_row" style="background-color:lightgray;">
	<div class='col-sm-6'>
		<h3 style="display:inline;">{{ tickets.ticket_title }}</h3>
		<div class="status_class">
		<h3 style="display:inline;">Status:</h3>
		{% if tickets.ticket_status == 1 %}
		<h3 style="color:red; display:inline;">Call Recieved</h3>
		{% elif tickets.ticket_status == 2 %}
		<h3 style="color:yellow; display:inline;">In Progress</h3>
		{% elif tickets.ticket_status == 3 %}
		<h3 style="color:blue; display:inline;">Waiting Customer</h3>
		{% elif tickets.ticket_status == 4 %}
		<h3 style="color:blue; display:inline;">Waiting Vendor</h3>
		{% elif tickets.ticket_status == 5 %}
		<h3 style="color:green; display:inline;">Complete</h3>
		{% endif %}
	</div>
	</div>
</div>
<div class="row">
	<div class='col-sm-3'>
		<h4 class='ticket_header-field'>Ticket Start Date: </h4>
		<h4 class='ticket_header-field'>Ticket Initiated by: </h4>
		<h4 class='ticket_header-field'>Total Time spent: </h4>
		<h4 class='ticket_header-field'>Client: </h4>
		<h4 class='ticket_header-field'>Contact Name: </h4>
	</div>
	<div class='col-sm-3'>
		<h4>{{ tickets.ticketstartdate }}</h4>
		<h4>{{ tickets.technician }}</h4>
		<h4>{{ tickets.time_spent_minutes_field }} minutes</h4>
		<h4>{{ tickets.clientid }}</h4>
		<h4>{{ tickets.contact_name }}</h4>
	</div>
</div>








<h4>Ticket Entries</h4>

{% for entries in entries %}
<div class="container" id="entrycontainer">
{{ entries.startdate }} {{ entries.enddate }} <br/>
{{ entries.worktype }}<br/>
<h5 class="tech">{{ entries.technician }}<br/></h5>
{{ entries.notes }} <br />
</div>
{% endfor %}
<form method="GET" action="{% url 'accounts:new_entry' %}">
	<button type="btn btn-default" value="{{ tickets.oid }}" name="editticket">Add New Time Entry</button>
</form>

<script>
	$('#entrycontainer > .tech').each(function(){
		var techname = $(this).text();
		if( techname == 'Mike') {
			$('#entrycontainer').attr('style','border-left:solid rgb(125,154,59,1) 10px');
		}
		if( techname == 'Ross') {
			$('#entrycontainer').attr('style','border-left:solid lightgrey 4px');
		}
		if( techname == 'Marcus') {
			$('#entrycontainer').attr('style','border-left:solid lightblue 4px');
		}
		if( techname == 'Aaron') {
			$('#entrycontainer').attr('style','border-left:solid maroon 4px');
		}
	});

</script>

{% endblock %}

accounts/templates/accounts/ticket-table.html
{% block tickettable %}
<div class="ticket_wall" id="ticket_window">
	{% block page_actionbar %}
    {% include 'accounts/toolbars/page_actionbar.html' %}
    {% endblock %}
<form method="GET" action="{% url 'accounts:ticket_detail' %}" id="profile_tickets">
<div class="tckt_container" id="ticket_container">		
		<div class="ticket_table" id="table">
			<div class="container" id="header">
				<div class="col-sm-2">Ticket Status</div>
				<div class="col-sm-5">Ticket Title</div>
				<div class="col-sm-5">Start Date</div>
			</div>
			<div class="container" id="tablebody">
			{% for tickets in tickets %}
			{% if tickets.ticket_status == 5 %}
			<button type='submit' name='tdetails' value="{{ tickets.oid }}" class="btn btn-block" id="success">				
				<div class="col-sm-2" id="status_col"><h2>Resolved</h2></div>
				<div class="col-sm-5" id="title_col"><h3>{{ tickets.ticket_title }}</h3></div>
				<div class="col-sm-5" id="date_col"><h3>{{ tickets.ticketstartdate }}<h3></div>
			</button>
			{% elif tickets.ticket_status == 1 %}
			<button type='submit' name='tdetails' value="{{ tickets.oid }}" class="btn btn-block" id="danger">				
				<div class="col-sm-2" id="status_col"><h2>Open</h2></div>
				<div class="col-sm-5" id="title_col"><h3>{{ tickets.ticket_title }}</h3></div>
				<div class="col-sm-5" id="date_col"><h3>{{ tickets.ticketstartdate }}</33></div>
			</button>			{% elif tickets.ticket_status == 1 %}
			<button type='submit' name='tdetails' value="{{ tickets.oid }}" class="btn btn-block" id="warning">				
				<div class="col-sm-2" id="status_col"><h2>Notsure</h2></div>
				<div class="col-sm-5" id="title_col"><h3>{{ tickets.ticket_title }}</h3></div>
				<div class="col-sm-5" id="date_col"><h3>{{ tickets.ticketstartdate }}</33></div>
			</button>			{% endif %}			 
				{% endfor %}
			</div>
		</div>
	</div>
</form>
</div>
{% endblock %}

accounts/templates/accounts/tickets.html
{% extends 'base.html' %}

{% block body %}

{% block tickettable %}
{% include 'accounts/ticket-table.html' %}
{% endblock %}


{% endblock %}

accounts/templates/accounts/tickets_slug.html
{% block body %}
{{ name.clientname }}
<div class="container" id="ticket_container">
		
		<table class="table table-row">
			<thead>
				<th>Ticket Status</th>
				<th>Ticket Title</th>
				<th>Start Date</th>
			</thead>
			<tbody>
			{% for tickets in tickets %}
				<tr>
					{% if tickets.ticket_status == 5 %}
					<td class="success">Resolved</td>
					{% elif tickets.ticket_status == 1 %}
					<td class="danger">Open</td>
					{% else %}
					<td class="warning">Not Sure</td>
					{% endif %}
					<td>{{ tickets.ticket_title }}</td>
					<td>{{ tickets.ticketstartdate }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

</div>
{% endblock %}